### ISSUE TITLE
jkimnejm Recommendations

### ISSUE THREAD

**Issue by jkimnejm** [githubteacher/developers-jan#17]
## Things to do in Boston, MA

Let's add a file for people who are visiting Boston for the first time!

### Steps for this project

- [x] Create a branch
- [x] Create a file
- [x] Commit my changes
- [x] Open a pull request
- [ ] Request a review
- [ ] Make changes as needed
- [ ] Get an Approval
- [ ] Merge the Pull Request

**Comment by svatasoiumms** [comment]
hi
